# Generated by Django 2.1.7 on 2019-04-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmovierate', '0002_remove_modelsignup_confpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelmovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=30)),
                ('movie_director', models.CharField(max_length=30)),
                ('movie_studio', models.CharField(max_length=40)),
                ('movie_year', models.CharField(max_length=10)),
            ],
        ),
    ]
