# Generated by Django 2.1.7 on 2019-04-25 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmovierate', '0005_modelmovie_movie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelmovie',
            name='movie_id',
        ),
    ]
