# Generated by Django 2.1.7 on 2019-04-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmovierate', '0007_modelrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelrating',
            name='ratings',
            field=models.IntegerField(),
        ),
    ]
