# Generated by Django 2.1.7 on 2019-04-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmovierate', '0008_auto_20190429_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrating',
            name='date',
            field=models.CharField(default='', max_length=200),
        ),
    ]
